# Generated by Django 2.2.16 on 2020-12-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
        migrations.AddField(
            model_name='article',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
